export const shopCategories = [
  { value: "art", label: "Art & Craft Supplies" },
  { value: "entertainment", label: "Entertainment & Gaming" },
  { value: "electronics", label: "Electronics & Accessories" },
  { value: "fashion", label: "Fashion & Apparel" },
  { value: "beauty", label: "Beauty & Personal Care" },
  { value: "home", label: "Home & Living" },
  { value: "kitchen", label: "Kitchen & Dining" },
  { value: "furniture", label: "Furniture" },
  { value: "books", label: "Books & Stationery" },
  { value: "toys", label: "Toys & Games" },
  { value: "sports", label: "Sports & Outdoor Equipment" },
  { value: "automotive", label: "Automotive & Tools" },
  { value: "garden", label: "Garden & Outdoor" },
  { value: "pets", label: "Pet Supplies" },
  { value: "health", label: "Health & Wellness" },
  { value: "groceries", label: "Groceries & Gourmet Food" },
  { value: "baby", label: "Baby & Kids" },
  { value: "office", label: "Office & School Supplies" },
  { value: "jewelry", label: "Jewelry & Accessories" },
  { value: "music", label: "Music & Instruments" },
  { value: "photography", label: "Cameras & Photography" },
  { value: "footwear", label: "Shoes & Footwear" },
  { value: "travel", label: "Travel & Luggage" },
  { value: "collectibles", label: "Collectibles & Memorabilia" },
  { value: "industrial", label: "Industrial & Scientific" },
  { value: "fitness", label: "Fitness & Gym Equipment" },
  { value: "outdoors", label: "Camping & Hiking Gear" },
  { value: "mobile", label: "Mobile Phones & Accessories" },
  { value: "computers", label: "Computers & Laptops" },
  { value: "smart_home", label: "Smart Home Devices" },
  { value: "audio", label: "Audio & Headphones" },
  { value: "video", label: "TVs & Video Equipment" },
  { value: "crafts", label: "DIY & Craft Kits" },
  { value: "lighting", label: "Lighting & Fixtures" },
  { value: "bath", label: "Bath & Cleaning Supplies" },
  { value: "party", label: "Party & Event Supplies" },
  { value: "seasonal", label: "Seasonal & Holiday Decor" },
  { value: "security", label: "Security & Surveillance" },
  { value: "software", label: "Software & Apps" },
  { value: "hardware", label: "Hardware & Building Materials" },
  { value: "wine", label: "Wine, Beer & Spirits" },
  { value: "medical", label: "Medical Supplies" },
  { value: "printing", label: "Printing & Custom Merchandise" },
  { value: "gifts", label: "Gifts & Occasions" },
  { value: "eco", label: "Eco-Friendly Products" },
  { value: "subscription", label: "Subscription Boxes" },
  { value: "luxury", label: "Luxury & Designer Items" },
  { value: "vintage", label: "Vintage & Retro Finds" },
  { value: "services", label: "Professional & Local Services" },
  { value: "digital", label: "Digital Goods & Downloads" },
  { value: "education", label: "Learning & Education" },
  { value: "events", label: "Tickets & Experiences" },
  { value: "other", label: "Other" },
];
